### ISSUE TITLE
[Feature]Add catalog support

### ISSUE THREAD

**Issue by lwpk110** [zncdatadev/dolphinscheduler-operator#32]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

TODO list:

- [x] update catalog phony to Makefile.
- [x] add basic catalog template
- [x] test pass catalog

ref:

- [Initializing the Catalog](https://olm.operatorframework.io/docs/tasks/creating-a-catalog/#initializing-the-catalog)

### Examples 🌈

update `Makefile`：
```makefile
# The image tag given to the resulting catalog image (e.g. make catalog-build CATALOG_IMG=example.com/operator-catalog:v0.2.0).
CATALOG_IMG ?= $(IMAGE_TAG_BASE)-catalog:latest

.PHONY: catalog-build
catalog-build: opm ## Build a catalog manifests.
	mkdir -p catalog
	@if ! test -f ./catalog.Dockerfile; then \
		$(OPM) generate dockerfile catalog; \
	fi
	sed -E "s|(image: ).*-bundle:v$(VERSION)|\1$(BUNDLE_IMG)|g" catalog-template.yaml | \
	$(OPM) alpha render-template basic -o yaml > catalog/catalog.yaml

.PHONY: catalog-docker-build
catalog-docker-build: ## Build a catalog image.
	$(CONTAINER_TOOL) build -t ${CATALOG_IMG} -f catalog.Dockerfile .

# Push the catalog image.
.PHONY: catalog-docker-push
catalog-docker-push: ## Push a catalog image.
	$(MAKE) docker-push IMG=$(CATALOG_IMG)

.PHONY: catalog-docker-buildx
catalog-docker-buildx: ## Build and push a catalog image for cross-platform support
	- $(CONTAINER_TOOL) buildx create --name project-v3-builder
	$(CONTAINER_TOOL) buildx use project-v3-builder
	- $(CONTAINER_TOOL) buildx build --push --platform=$(PLATFORMS) -f catalog.Dockerfile --tag ${CATALOG_IMG} .
	- $(CONTAINER_TOOL) buildx rm project-v3-builder
```

create `catalog-template.yaml`
```yaml
---
defaultChannel: stable
description: |
    ...
icon:
  base64data: PHN2ZyBpZD...
  mediatype: image/svg+xml
name: trino-operator
schema: olm.package
---
schema: olm.channel
package: trino-operator
name: stable
entries:
  - name: trino-operator.v0.0.1
---
schema: olm.bundle
image: quay.io/zncdata/trino-operator-bundle:v0.0.1
```

### Motivation 🔦

By updating bundle and catalog building, so that we can build a dolphinscheduler-cluster on a kubernets cluster quickly
